"""mensaje opcional

Revision ID: 564adf2a723f
Revises: 
Create Date: 2025-05-18 15:48:31.186360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564adf2a723f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiante',
    sa.Column('ci', sa.Integer(), nullable=False),
    sa.Column('nombreCompleto', sa.String(length=50), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('contrasena', sa.String(length=255), nullable=True),
    sa.Column('apoderado', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ci'),
    sa.UniqueConstraint('ci')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estudiante')
    # ### end Alembic commands ###
